<script setup>
import AdminLayout from '../../../Layouts/AdminLayout.vue';
import { Head, Link, router } from '@inertiajs/vue3';
import { reactive } from 'vue';

const props = defineProps({ reports: Object, filters: Object, counts: Object, pageSizes: Array });
const filter = reactive({ ...props.filters });
const reasons = { spam: 'Spam veya reklam', harassment: 'Taciz veya hakaret', fraud: 'Dolandırıcılık şüphesi', personal_data: 'Kişisel bilgi paylaşımı', other: 'Diğer' };
const statuses = { pending: 'İncelenecek', confirmed: 'İhlal doğrulandı', dismissed: 'Reddedildi' };
const statusClasses = { pending: 'bg-amber-50 text-amber-900', confirmed: 'bg-red-50 text-red-800', dismissed: 'bg-slate-100 text-slate-700' };
const applyFilters = () => router.get('/admin/message-reports', { ...filter, search: filter.search || undefined, status: filter.status || undefined, reason: filter.reason || undefined }, { preserveState: true, replace: true });
const setStatus = status => { filter.status = status; applyFilters(); };
const clearFilters = () => { Object.assign(filter, { search: '', status: '', reason: '', per_page: 50 }); applyFilters(); };
</script>

<template>
  <Head title="Mesaj Bildirimleri" />
  <AdminLayout eyebrow="Güvenlik" title="Bildirilen mesajlar" description="Bildirilen konuşmaları bağlamıyla incele, ihlal kararını ve uygulanacak yaptırımı denetlenebilir biçimde kaydet.">
    <main class="mx-auto max-w-[1600px] px-5 py-8 lg:px-8">
      <section class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><button v-for="item in [['', 'Tüm bildirimler', counts.all], ['pending', 'İncelenecek', counts.pending], ['confirmed', 'Doğrulandı', counts.confirmed], ['dismissed', 'Reddedildi', counts.dismissed]]" :key="item[0]" type="button" @click="setStatus(item[0])" :class="['rounded-2xl border bg-white p-5 text-left transition', (filter.status || '') === item[0] ? 'border-emerald-500 ring-2 ring-emerald-100' : 'border-slate-200 hover:border-slate-300']"><p class="text-sm font-semibold text-slate-700">{{ item[1] }}</p><p class="mt-2 text-3xl font-semibold text-slate-950">{{ Number(item[2]).toLocaleString('tr-TR') }}</p></button></section>
      <section class="mt-5 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><form class="grid gap-3 xl:grid-cols-[1fr_210px_210px_140px_auto]" @submit.prevent="applyFilters"><label class="text-xs font-semibold text-slate-700">Bildirim, kullanıcı veya mesaj ara<input v-model="filter.search" maxlength="120" class="mt-1.5 h-11 w-full rounded-xl border border-slate-300 px-3 text-sm text-slate-950 outline-none focus:border-emerald-600 focus:ring-2 focus:ring-emerald-100" placeholder="Numara, ad, e-posta veya mesaj" /></label><label class="text-xs font-semibold text-slate-700">Durum<select v-model="filter.status" class="mt-1.5 h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm"><option value="">Tümü</option><option v-for="(label, value) in statuses" :key="value" :value="value">{{ label }}</option></select></label><label class="text-xs font-semibold text-slate-700">Bildirim nedeni<select v-model="filter.reason" class="mt-1.5 h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm"><option value="">Tümü</option><option v-for="(label, value) in reasons" :key="value" :value="value">{{ label }}</option></select></label><label class="text-xs font-semibold text-slate-700">Sayfa başına<select v-model.number="filter.per_page" class="mt-1.5 h-11 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm"><option v-for="size in pageSizes" :key="size" :value="size">{{ size }}</option></select></label><div class="flex items-end gap-2"><button class="h-11 rounded-xl bg-forest-700 px-5 text-sm font-semibold text-white">Uygula</button><button type="button" class="h-11 rounded-xl border border-slate-300 px-4 text-sm font-semibold text-slate-700" @click="clearFilters">Temizle</button></div></form></section>
      <section class="mt-5 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-200 px-5 py-4"><div><h2 class="text-lg font-semibold text-slate-950">Mesaj bildirimi kayıtları</h2><p class="mt-1 text-sm text-slate-600">{{ reports.total.toLocaleString('tr-TR') }} sonuç</p></div><p class="text-sm text-slate-600">Sayfa {{ reports.current_page }} / {{ reports.last_page }}</p></div><div v-if="reports.data.length" class="overflow-x-auto"><table class="w-full min-w-[1180px] text-left text-sm"><thead class="border-b border-slate-200 bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-700"><tr><th class="px-5 py-3.5">Bildirim</th><th class="px-5 py-3.5">Mesaj ve bölge</th><th class="px-5 py-3.5">Bildirilen kullanıcı</th><th class="px-5 py-3.5">Bildiren</th><th class="px-5 py-3.5">Durum</th><th class="px-5 py-3.5 text-right">İşlem</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="report in reports.data" :key="report.id" class="text-slate-800 hover:bg-slate-50"><td class="px-5 py-4"><p class="font-semibold text-slate-950">#{{ report.id }}</p><p class="mt-1 text-xs font-medium text-red-700">{{ reasons[report.reason] }}</p><p class="mt-1 text-xs text-slate-600">{{ $adminDate(report.created_at) }} · Görüşme #{{ report.conversation_id }}</p></td><td class="max-w-sm px-5 py-4"><p class="line-clamp-2 leading-5 text-slate-800">{{ report.message.body }}</p><p class="mt-1 text-xs text-slate-600">{{ report.listing_area || 'Bölge bilgisi yok' }}</p></td><td class="px-5 py-4"><p class="font-semibold text-slate-950">{{ report.reported_user?.name || 'Silinmiş kullanıcı' }}</p><p class="mt-0.5 text-xs text-slate-600">{{ report.reported_user?.email }}</p></td><td class="px-5 py-4"><p class="font-semibold text-slate-950">{{ report.reporter.name }}</p><p class="mt-0.5 text-xs text-slate-600">{{ report.reporter.email }}</p></td><td class="px-5 py-4"><span :class="['rounded-full px-2.5 py-1 text-xs font-semibold', statusClasses[report.status]]">{{ statuses[report.status] }}</span></td><td class="px-5 py-4 text-right"><Link :href="`/admin/message-reports/${report.id}`" title="Bildirimi incele" aria-label="Bildirimi incele" class="inline-grid size-9 place-items-center rounded-lg border border-slate-300 text-slate-700 hover:border-emerald-500 hover:text-emerald-700"><svg viewBox="0 0 24 24" class="size-4" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/></svg></Link></td></tr></tbody></table></div><div v-else class="px-5 py-16 text-center"><p class="font-semibold text-slate-900">Bu filtrelerde mesaj bildirimi bulunamadı.</p><button type="button" class="mt-3 text-sm font-semibold text-emerald-700" @click="clearFilters">Filtreleri temizle</button></div></section>
      <nav v-if="reports.last_page > 1" class="mt-5 flex flex-wrap gap-2"><Link v-for="link in reports.links" :key="link.label" :href="link.url || ''" :class="['rounded-lg border px-3 py-2 text-sm font-semibold', link.active ? 'border-emerald-600 bg-emerald-50 text-emerald-800' : 'border-slate-300 bg-white text-slate-700', !link.url && 'pointer-events-none opacity-40']" v-html="link.label" /></nav>
    </main>
  </AdminLayout>
</template>
