import { StyleSheet } from 'react-native';
import { C } from './styles';

export const ds = StyleSheet.create({
  screen: { flex: 1, backgroundColor: C.bg },
  topBar: { height: 58, paddingHorizontal: 18, flexDirection: 'row', alignItems: 'center', borderBottomWidth: 1, borderBottomColor: C.line, backgroundColor: C.bg },
  backButton: { width: 40, height: 40, borderRadius: 20, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, alignItems: 'center', justifyContent: 'center' },
  backText: { color: C.ink, fontSize: 25, lineHeight: 27 },
  topTitle: { flex: 1, color: C.ink, fontSize: 16, fontWeight: '900', textAlign: 'center' },
  topSpacer: { width: 40 },
  detailContent: { paddingBottom: 18 },
  visual: { height: 190, margin: 18, marginBottom: 14, borderRadius: 25, backgroundColor: C.dark, overflow: 'hidden', padding: 20, justifyContent: 'flex-end' },
  visualCircleOne: { position: 'absolute', width: 155, height: 155, borderRadius: 78, backgroundColor: '#286E4E', right: -30, top: -32 },
  visualCircleTwo: { position: 'absolute', width: 95, height: 95, borderRadius: 48, backgroundColor: '#B9DD75', right: 52, top: 38 },
  visualBottle: { position: 'absolute', right: 78, top: 30, color: C.dark, fontSize: 56, fontWeight: '900' },
  statusPill: { alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 10, backgroundColor: C.lime, marginBottom: 9 },
  statusPillText: { color: C.dark, fontSize: 11, fontWeight: '900' },
  visualTitle: { color: C.white, fontSize: 27, fontWeight: '900', letterSpacing: -.7 },
  visualSub: { color: '#BCD0C4', fontSize: 12, marginTop: 4 },
  section: { marginHorizontal: 18, marginBottom: 12, padding: 16, borderRadius: 20, backgroundColor: C.white, borderWidth: 1, borderColor: C.line },
  sectionLabel: { color: C.muted, fontSize: 11, letterSpacing: 1.1, fontWeight: '900', marginBottom: 11 },
  itemRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 9, borderBottomWidth: 1, borderBottomColor: C.line },
  itemCopy: { flex: 1, marginLeft: 10 },
  itemName: { color: C.ink, fontSize: 13, fontWeight: '900' },
  itemUnit: { color: C.muted, fontSize: 11, marginTop: 2 },
  itemTotal: { color: C.ink, fontSize: 14, fontWeight: '900' },
  totals: { flexDirection: 'row', alignItems: 'stretch', gap: 9, marginTop: 13 },
  totalBox: { flex: 1, borderRadius: 14, padding: 12, backgroundColor: '#F5F7F4' },
  gainTotalBox: { backgroundColor: C.soft },
  totalLabel: { color: C.muted, fontSize: 10, marginBottom: 4 },
  totalValue: { color: C.ink, fontSize: 17, fontWeight: '900' },
  gainTotal: { color: C.green },
  infoRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 13 },
  infoIcon: { width: 36, height: 36, borderRadius: 12, backgroundColor: C.soft, alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  infoIconText: { color: C.green, fontSize: 18, fontWeight: '900' },
  infoCopy: { flex: 1 },
  infoLabel: { color: C.muted, fontSize: 11, marginBottom: 3 },
  infoValue: { color: C.ink, fontSize: 12, fontWeight: '800' },
  safetyText: { color: C.muted, fontSize: 11, lineHeight: 16, padding: 10, borderRadius: 11, backgroundColor: '#F8F5EC' },
  seller: { flexDirection: 'row', alignItems: 'center' },
  sellerAvatar: { width: 51, height: 51, borderRadius: 26, backgroundColor: C.lime, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  sellerAvatarText: { color: C.dark, fontSize: 20, fontWeight: '900' },
  sellerCopy: { flex: 1 },
  sellerName: { color: C.ink, fontSize: 15, fontWeight: '900' },
  sellerMeta: { color: C.muted, fontSize: 12, marginTop: 4 },
  sellerRating: { color: C.orange, fontSize: 12, fontWeight: '900' },
  noteText: { color: C.ink, fontSize: 12, lineHeight: 18 },
  reportButton: { marginHorizontal: 18, marginBottom: 12, minHeight: 58, borderRadius: 16, borderWidth: 1, borderColor: '#E8C1B9', backgroundColor: '#FFF7F5', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 14, paddingVertical: 10 },
  reportText: { color: '#A04C38', fontSize: 12, fontWeight: '900', textAlign: 'center' },
  reportHelp: { color: '#916E67', fontSize: 11, lineHeight: 16, textAlign: 'center', marginTop: 3 },
  reportProvider: { flex: 1 },
  reportBackdrop: { flex: 1, justifyContent: 'flex-end' },
  reportBackdropPress: { position: 'absolute', top: 0, right: 0, bottom: 0, left: 0, backgroundColor: 'rgba(11,25,17,.48)' },
  reportSheet: { maxHeight: '90%', borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: C.white, paddingHorizontal: 18, paddingTop: 18, paddingBottom: 16 },
  reportTitle: { color: C.ink, fontSize: 18, fontWeight: '900' },
  reportSubtitle: { color: C.muted, fontSize: 12, lineHeight: 18, marginTop: 4, marginBottom: 12 },
  reportScroll: { flexShrink: 1 },
  reportScrollContent: { paddingBottom: 4 },
  reportOptions: { gap: 7, marginBottom: 12 },
  reportInput: { minHeight: 76, maxHeight: 118, borderRadius: 14, backgroundColor: C.bg, borderWidth: 1, borderColor: C.line, padding: 11, color: C.ink, fontSize: 13, textAlignVertical: 'top' },
  reportOption: { minHeight: 46, flexDirection: 'row', alignItems: 'center', gap: 10, borderWidth: 1, borderColor: C.line, borderRadius: 13, paddingHorizontal: 12, backgroundColor: C.white },
  reportOptionSelected: { borderColor: C.green, backgroundColor: C.soft },
  reportRadio: { width: 20, height: 20, borderRadius: 10, borderWidth: 1.5, borderColor: '#A6B1AA', alignItems: 'center', justifyContent: 'center' },
  reportRadioSelected: { borderColor: C.green },
  reportRadioDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: C.green },
  reportOptionText: { color: C.ink, fontSize: 13, fontWeight: '800' },
  reportOptionTextSelected: { color: C.green },
  reportActions: { flexDirection: 'row', gap: 10, marginTop: 14 },
  reportCancel: { minHeight: 48, flex: 1, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: C.line, borderRadius: 14, backgroundColor: C.white },
  reportCancelText: { color: C.muted, fontSize: 13, fontWeight: '900' },
  reportSubmit: { minHeight: 48, flex: 1.35, alignItems: 'center', justifyContent: 'center', borderRadius: 14, backgroundColor: C.green },
  reportSubmitDisabled: { opacity: 0.45 },
  reportSubmitText: { color: C.white, fontSize: 13, fontWeight: '900' },
  detailActions: { padding: 12, paddingBottom: 13, flexDirection: 'row', gap: 9, backgroundColor: C.white, borderTopWidth: 1, borderTopColor: C.line },
  secondaryAction: { flex: 1, height: 53, borderRadius: 16, borderWidth: 1.5, borderColor: C.green, alignItems: 'center', justifyContent: 'center' },
  secondaryActionText: { color: C.green, fontSize: 12, fontWeight: '900' },
  primaryAction: { flex: 1.35, height: 53, borderRadius: 16, backgroundColor: C.green, alignItems: 'center', justifyContent: 'center' },
  primaryActionText: { color: C.white, fontSize: 12, fontWeight: '900' },
  requestSent: { backgroundColor: '#D9A136' },
  chatHeader: { minHeight: 65, paddingHorizontal: 15, flexDirection: 'row', alignItems: 'center', backgroundColor: C.white, borderBottomWidth: 1, borderBottomColor: C.line },
  chatAvatar: { width: 42, height: 42, borderRadius: 21, backgroundColor: C.lime, alignItems: 'center', justifyContent: 'center', marginLeft: 10, marginRight: 10 },
  chatAvatarText: { color: C.dark, fontSize: 16, fontWeight: '900' },
  chatHeaderCopy: { flex: 1 },
  chatName: { color: C.ink, fontSize: 14, fontWeight: '900' },
  chatOnline: { color: C.green, fontSize: 11, marginTop: 2 },
  listingStrip: { margin: 11, marginBottom: 4, padding: 11, borderRadius: 15, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, flexDirection: 'row', alignItems: 'center' },
  listingStripCopy: { flex: 1 },
  listingStripTitle: { color: C.ink, fontSize: 12, fontWeight: '900' },
  listingStripSub: { color: C.muted, fontSize: 11, marginTop: 3 },
  listingStripPrice: { color: C.green, fontSize: 13, fontWeight: '900' },
  pendingBanner: { marginHorizontal: 11, marginTop: 7, padding: 11, borderRadius: 13, backgroundColor: '#FFF4D9', borderWidth: 1, borderColor: '#EFD89D', flexDirection: 'row', alignItems: 'center' },
  pendingIcon: { color: '#A36D0B', fontSize: 20, marginRight: 9 },
  pendingCopy: { flex: 1 },
  pendingTitle: { color: '#855A0C', fontSize: 12, fontWeight: '900' },
  pendingText: { color: '#92743B', fontSize: 10, marginTop: 2 },
  messages: { flex: 1 },
  messagesContent: { padding: 12, paddingBottom: 16 },
  bubbleRow: { marginBottom: 9, flexDirection: 'row' },
  bubbleRowMe: { justifyContent: 'flex-end' },
  bubble: { maxWidth: '79%', borderRadius: 17, borderBottomLeftRadius: 5, paddingHorizontal: 12, paddingVertical: 9, backgroundColor: C.white, borderWidth: 1, borderColor: C.line },
  bubbleMe: { backgroundColor: C.green, borderColor: C.green, borderBottomLeftRadius: 17, borderBottomRightRadius: 5 },
  bubbleSystem: { maxWidth: '100%', width: '100%', backgroundColor: C.soft, borderColor: '#C7DDCD', borderRadius: 13 },
  bubbleText: { color: C.ink, fontSize: 12, lineHeight: 18 },
  bubbleTextMe: { color: C.white },
  bubbleTime: { color: C.muted, fontSize: 10, textAlign: 'right', marginTop: 4 },
  bubbleTimeMe: { color: '#C7DDD0' },
  emptyChat: { alignItems: 'center', padding: 25 },
  emptyChatIcon: { fontSize: 34, color: C.green, marginBottom: 8 },
  emptyChatTitle: { color: C.ink, fontSize: 14, fontWeight: '900' },
  emptyChatText: { color: C.muted, fontSize: 12, textAlign: 'center', lineHeight: 18, marginTop: 5 },
  quickArea: { paddingTop: 7, paddingBottom: 4, backgroundColor: C.white, borderTopWidth: 1, borderTopColor: C.line },
  quickScroll: { paddingHorizontal: 10, gap: 7 },
  quickChip: { height: 35, paddingHorizontal: 12, borderRadius: 18, borderWidth: 1, borderColor: '#BCD4C3', alignItems: 'center', justifyContent: 'center' },
  quickText: { color: C.green, fontSize: 11, fontWeight: '800' },
  composer: { paddingHorizontal: 10, paddingVertical: 8, flexDirection: 'row', alignItems: 'flex-end', gap: 8, backgroundColor: C.white },
  chatInput: { flex: 1, minHeight: 44, maxHeight: 90, borderRadius: 17, backgroundColor: '#F3F6F2', borderWidth: 1, borderColor: C.line, paddingHorizontal: 13, paddingVertical: 11, color: C.ink, fontSize: 12 },
  sendButton: { width: 44, height: 44, borderRadius: 22, backgroundColor: C.green, alignItems: 'center', justifyContent: 'center' },
  sendText: { color: C.white, fontSize: 19, fontWeight: '900' },
});
