import { StyleSheet } from 'react-native';
import { C } from './styles';

export const ls = StyleSheet.create({
  selectorCopy: { flex: 1, paddingRight: 10 },
  selectorTitleRow: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 3 },
  modeBadge: { borderRadius: 7, paddingHorizontal: 6, paddingVertical: 3, backgroundColor: '#EEF0ED' },
  modeBadgeCurrent: { backgroundColor: '#DFF2E4' },
  modeBadgeText: { color: C.muted, fontSize: 10, letterSpacing: .5, fontWeight: '900' },
  modeBadgeTextCurrent: { color: C.green },
  radiusText: { color: C.green, fontSize: 12, fontWeight: '700', marginTop: 3 },
  emptyState: { marginHorizontal: 20, marginTop: 4, padding: 28, borderRadius: 22, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, alignItems: 'center' },
  emptyIcon: { width: 58, height: 58, borderRadius: 29, backgroundColor: C.soft, alignItems: 'center', justifyContent: 'center', marginBottom: 13 },
  emptyIconText: { color: C.green, fontSize: 30, fontWeight: '900' },
  emptyTitle: { color: C.ink, fontSize: 17, fontWeight: '900' },
  emptyText: { color: C.muted, fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 6 },
  emptyButton: { marginTop: 15, paddingHorizontal: 17, height: 42, borderRadius: 14, backgroundColor: C.green, alignItems: 'center', justifyContent: 'center' },
  emptyButtonText: { color: C.white, fontSize: 12, fontWeight: '900' },
  locationSheet: { maxHeight: '94%' },
  currentSummary: { flexDirection: 'row', alignItems: 'center', borderRadius: 16, padding: 13, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, marginBottom: 11 },
  summaryIcon: { width: 42, height: 42, borderRadius: 21, backgroundColor: C.soft, alignItems: 'center', justifyContent: 'center', marginRight: 11 },
  summaryIconText: { color: C.green, fontSize: 22, fontWeight: '900' },
  summaryCopy: { flex: 1 },
  summaryLabel: { color: C.muted, fontSize: 11, marginBottom: 3 },
  summaryValue: { color: C.ink, fontSize: 14, fontWeight: '900' },
  liveDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: '#38A969', borderWidth: 2, borderColor: '#DFF2E4' },
  currentButton: { minHeight: 64, borderRadius: 17, padding: 13, backgroundColor: C.green, flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
  disabled: { opacity: .75 },
  currentButtonIcon: { color: C.white, fontSize: 27, width: 39, textAlign: 'center', marginRight: 5 },
  currentButtonCopy: { flex: 1 },
  currentButtonTitle: { color: C.white, fontSize: 13, fontWeight: '900' },
  currentButtonText: { color: '#C7DDD0', fontSize: 11, marginTop: 3 },
  groupLabel: { color: C.muted, fontSize: 11, letterSpacing: 1.3, fontWeight: '900', marginBottom: 9 },
  radiusGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 12 },
  radiusOption: { width: '30.8%', height: 50, borderRadius: 14, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, flexDirection: 'row', alignItems: 'baseline', justifyContent: 'center', paddingTop: 11 },
  radiusOptionActive: { backgroundColor: C.dark, borderColor: C.dark },
  radiusOptionValue: { color: C.ink, fontSize: 16, fontWeight: '900' },
  radiusOptionValueActive: { color: C.white },
  radiusOptionUnit: { color: C.muted, fontSize: 11, fontWeight: '700', marginLeft: 3 },
  radiusOptionUnitActive: { color: '#BFD1C6' },
  resultBanner: { borderRadius: 13, padding: 11, backgroundColor: C.soft, flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
  resultNumber: { color: C.green, fontSize: 20, fontWeight: '900', marginRight: 8 },
  resultText: { color: C.green, fontSize: 12, lineHeight: 18, flex: 1, fontWeight: '700' },
  manualList: { borderRadius: 17, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, overflow: 'hidden' },
  manualRow: { minHeight: 49, flexDirection: 'row', alignItems: 'center', paddingHorizontal: 13, borderBottomWidth: 1, borderBottomColor: C.line },
  manualPin: { width: 27, height: 27, borderRadius: 14, backgroundColor: C.soft, alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  manualPinText: { color: C.green, fontSize: 11 },
  manualLabel: { color: C.ink, fontSize: 12, fontWeight: '800', flex: 1 },
  manualArrow: { color: C.muted, fontSize: 22 },
  privacyNote: { color: C.muted, fontSize: 11, lineHeight: 16, marginTop: 13, paddingHorizontal: 3 },
});
