import { StyleSheet } from 'react-native';

export const C = {
  bg: '#F4F7F2',
  white: '#FFFFFF',
  ink: '#16231C',
  muted: '#718077',
  line: '#E3E9E2',
  green: '#176B45',
  dark: '#0F4E32',
  lime: '#CDEA79',
  soft: '#E8F4E9',
  orange: '#F3A83B',
};

export const s = StyleSheet.create({
  app: { flex: 1, backgroundColor: C.bg },
  content: { flex: 1 },
  flex: { flex: 1 },
  pageBottom: { paddingBottom: 28 },
  pressed: { opacity: .82, transform: [{ scale: .99 }] },
  header: { paddingHorizontal: 20, paddingTop: 8, paddingBottom: 18, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  eyebrow: { color: C.green, fontSize: 12, letterSpacing: 1.7, fontWeight: '900' },
  logo: { color: C.ink, fontSize: 30, lineHeight: 34, fontWeight: '900', letterSpacing: -1.5, marginTop: 5 },
  logoDot: { color: C.green },
  notification: { width: 44, height: 44, borderRadius: 22, backgroundColor: C.white, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: C.line },
  notificationIcon: { fontSize: 23, color: C.ink },
  redDot: { position: 'absolute', width: 8, height: 8, borderRadius: 4, backgroundColor: '#EA6045', right: 9, top: 8, borderWidth: 2, borderColor: C.white },
  notificationBadge: { position: 'absolute', top: -5, right: -6, minWidth: 20, height: 20, paddingHorizontal: 4, borderRadius: 10, backgroundColor: '#D84D3F', borderWidth: 2, borderColor: C.bg, alignItems: 'center', justifyContent: 'center' },
  notificationBadgeText: { color: C.white, fontSize: 10, fontWeight: '900' },
  locationSelector: { marginHorizontal: 20, marginBottom: 16, padding: 14, paddingLeft: 16, borderRadius: 17, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  selectorLabel: { fontSize: 12, color: C.muted, marginBottom: 3 },
  selectorValue: { fontSize: 15, color: C.ink, fontWeight: '800' },
  locationCircle: { width: 38, height: 38, borderRadius: 19, backgroundColor: C.soft, alignItems: 'center', justifyContent: 'center' },
  locationCircleText: { color: C.green, fontSize: 22, fontWeight: '800' },
  hero: { marginHorizontal: 20, marginBottom: 16, minHeight: 184, padding: 20, borderRadius: 26, backgroundColor: C.dark, overflow: 'hidden', flexDirection: 'row' },
  heroCopy: { flex: 1, zIndex: 2 },
  heroKicker: { color: C.lime, fontSize: 12, letterSpacing: 1.8, fontWeight: '900', marginBottom: 8 },
  heroTitle: { color: C.white, fontSize: 27, lineHeight: 29, fontWeight: '900', letterSpacing: -.7 },
  heroText: { color: '#BCD0C4', fontSize: 12, lineHeight: 17, marginTop: 11 },
  heroArt: { width: 130, position: 'relative' },
  bottle: { position: 'absolute', width: 49, height: 112, right: 16, top: 28, borderRadius: 16, backgroundColor: '#7FC798', transform: [{ rotate: '9deg' }], alignItems: 'center', justifyContent: 'center' },
  can: { position: 'absolute', width: 46, height: 78, left: 10, top: 60, borderRadius: 11, backgroundColor: C.lime, transform: [{ rotate: '-13deg' }], alignItems: 'center', justifyContent: 'center' },
  artSymbol: { color: C.dark, fontSize: 25, fontWeight: '900' },
  coinOne: { position: 'absolute', width: 29, height: 29, borderRadius: 15, right: 4, top: 5, backgroundColor: C.orange, alignItems: 'center', justifyContent: 'center' },
  coinTwo: { position: 'absolute', width: 23, height: 23, borderRadius: 12, left: 30, top: 20, backgroundColor: '#F8C768', alignItems: 'center', justifyContent: 'center' },
  coinText: { color: '#664411', fontSize: 13, fontWeight: '900' },
  sectionHeading: { paddingHorizontal: 20, marginTop: 0, marginBottom: 14, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between' },
  sectionTitle: { color: C.ink, fontSize: 21, fontWeight: '900', letterSpacing: -.4 },
  sectionSub: { color: C.muted, fontSize: 12, marginTop: 3 },
  filterButton: { minHeight: 40, paddingHorizontal: 10, alignItems: 'center', justifyContent: 'center', marginRight: -10, marginBottom: -8 },
  filterText: { color: C.green, fontSize: 12, fontWeight: '800' },
  chipRow: { paddingHorizontal: 20, gap: 8, paddingBottom: 14 },
  sortPanel: { marginHorizontal: 20, marginBottom: 14, padding: 14, borderRadius: 17, backgroundColor: C.white, borderWidth: 1, borderColor: C.line },
  sortPanelTitle: { color: C.muted, fontSize: 11, letterSpacing: 1.2, fontWeight: '900', marginBottom: 10 },
  sortOptions: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  sortOption: { minHeight: 38, paddingHorizontal: 13, borderRadius: 12, backgroundColor: '#F5F7F4', borderWidth: 1, borderColor: C.line, alignItems: 'center', justifyContent: 'center' },
  sortOptionActive: { backgroundColor: C.dark, borderColor: C.dark },
  sortOptionText: { color: C.muted, fontSize: 12, fontWeight: '800' },
  sortOptionTextActive: { color: C.white },
  listFooter: { minHeight: 66, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9 },
  listFooterText: { color: C.muted, fontSize: 12, fontWeight: '700' },
  chip: { minHeight: 44, paddingHorizontal: 18, borderRadius: 19, alignItems: 'center', justifyContent: 'center', backgroundColor: C.white, borderWidth: 1, borderColor: C.line },
  chipActive: { backgroundColor: C.ink, borderColor: C.ink },
  chipText: { color: C.muted, fontWeight: '700', fontSize: 12 },
  chipTextActive: { color: C.white },
  adCard: { marginHorizontal: 20, marginBottom: 13, padding: 18, minHeight: 142, borderRadius: 22, borderWidth: 1, borderColor: '#C9DDCD', justifyContent: 'center' },
  adTopRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, marginBottom: 10 },
  adSponsor: { flex: 1, color: C.green, fontSize: 12, fontWeight: '900' },
  adLabel: { color: C.muted, fontSize: 11, letterSpacing: 1.1, fontWeight: '900' },
  adHeadline: { color: C.ink, fontSize: 20, lineHeight: 26, fontWeight: '900' },
  adBody: { color: C.muted, fontSize: 13, lineHeight: 20, marginTop: 7 },
  adCta: { color: C.green, fontSize: 13, fontWeight: '900', marginTop: 12 },
  card: { marginHorizontal: 20, marginBottom: 13, padding: 15, borderRadius: 22, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, shadowColor: '#183023', shadowOffset: { width: 0, height: 5 }, shadowOpacity: .05, shadowRadius: 12, elevation: 2 },
  cardTop: { flexDirection: 'row', alignItems: 'center' },
  materialStack: { height: 42, position: 'relative', marginRight: 8 },
  stackedIcon: { position: 'absolute', top: 0 },
  smallMaterialIcon: { width: 42, height: 42, borderRadius: 14, borderWidth: 2, borderColor: C.white, alignItems: 'center', justifyContent: 'center' },
  cardTitleArea: { flex: 1 },
  cardActions: { minWidth: 52, alignItems: 'flex-end', gap: 7, marginLeft: 7 },
  favoriteButton: { width: 42, height: 42, borderRadius: 16, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, alignItems: 'center', justifyContent: 'center' },
  favoriteButtonActive: { backgroundColor: '#FFF0ED', borderColor: '#E9B8AF' },
  favoriteIcon: { color: C.muted, fontSize: 22, lineHeight: 25 },
  favoriteIconActive: { color: '#C84F3D' },
  ownListingBadge: { minHeight: 27, paddingHorizontal: 8, borderRadius: 9, backgroundColor: C.soft, alignItems: 'center', justifyContent: 'center' },
  ownListingBadgeText: { color: C.green, fontSize: 10, letterSpacing: .4, fontWeight: '900' },
  titleLine: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  countText: { color: C.ink, fontSize: 17, fontWeight: '900' },
  tinyDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: C.line },
  timeText: { color: C.muted, fontSize: 12 },
  boostedBadge: { minHeight: 22, borderRadius: 11, paddingHorizontal: 7, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E8F4B8' },
  boostedBadgeInline: { alignSelf: 'flex-start', minHeight: 22, borderRadius: 11, paddingHorizontal: 8, marginTop: 7, alignItems: 'center', justifyContent: 'center', backgroundColor: '#E8F4B8' },
  boostedBadgeText: { color: C.dark, fontSize: 10, fontWeight: '900', letterSpacing: 0.35 },
  materialText: { color: C.muted, fontSize: 12, marginTop: 3 },
  distancePill: { paddingHorizontal: 9, paddingVertical: 7, borderRadius: 14, backgroundColor: C.soft },
  distanceText: { color: C.green, fontSize: 12, fontWeight: '800' },
  breakdown: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: 12 },
  breakdownChip: { paddingHorizontal: 9, paddingVertical: 6, borderRadius: 10, backgroundColor: '#F5F7F4', flexDirection: 'row', gap: 5 },
  breakdownName: { color: C.ink, fontSize: 11, fontWeight: '900' },
  breakdownValue: { color: C.muted, fontSize: 11, fontWeight: '700' },
  locationRow: { marginTop: 10, paddingVertical: 9, paddingHorizontal: 11, backgroundColor: '#F7F9F6', borderRadius: 11 },
  locationText: { color: C.muted, fontSize: 12, fontWeight: '600' },
  moneyRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginVertical: 14 },
  moneyLabel: { color: C.muted, fontSize: 12, marginBottom: 2 },
  moneyValue: { color: C.ink, fontSize: 19, fontWeight: '900' },
  gainBox: { backgroundColor: C.soft, borderRadius: 14, paddingVertical: 9, paddingHorizontal: 12, alignItems: 'flex-end' },
  gainLabel: { color: C.green, fontSize: 11, marginBottom: 2 },
  gainValue: { color: C.dark, fontSize: 16, fontWeight: '900' },
  sellerRow: { paddingTop: 12, borderTopWidth: 1, borderTopColor: C.line, flexDirection: 'row', alignItems: 'center' },
  avatar: { width: 29, height: 29, borderRadius: 15, backgroundColor: '#E7D8C8', alignItems: 'center', justifyContent: 'center', marginRight: 8 },
  avatarText: { color: C.ink, fontSize: 12, fontWeight: '900' },
  sellerCopy: { flex: 1, minWidth: 0, marginLeft: 10 },
  sellerName: { color: C.ink, fontSize: 12, fontWeight: '800' },
  sellerStatus: { color: C.muted, fontSize: 11, fontWeight: '700', marginTop: 3 },
  rating: { color: C.orange, fontSize: 12, fontWeight: '800', marginLeft: 7 },
  detailLink: { color: C.green, fontSize: 12, fontWeight: '900' },
  nav: { paddingTop: 7, paddingHorizontal: 7, backgroundColor: C.white, borderTopWidth: 1, borderTopColor: C.line, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-around' },
  navItem: { width: 67, minHeight: 58, alignItems: 'center', justifyContent: 'center', gap: 3 },
  navIconWrap: { minWidth: 40, height: 32, alignItems: 'center', justifyContent: 'center', position: 'relative' },
  rankingNavIcon: { color: '#8B9990', fontSize: 29, lineHeight: 32 },
  navBadge: { position: 'absolute', top: -5, right: -9, minWidth: 19, height: 19, borderRadius: 10, paddingHorizontal: 4, backgroundColor: '#D84D3F', borderWidth: 2, borderColor: C.white, alignItems: 'center', justifyContent: 'center' },
  navBadgeText: { color: C.white, fontSize: 10, fontWeight: '900' },
  navLabel: { color: '#8B9990', fontSize: 12, fontWeight: '700' },
  navActive: { color: C.green, fontWeight: '900' },
  createWrap: { width: 72, alignItems: 'center', marginTop: -29 },
  createButton: { width: 62, height: 62, borderRadius: 31, backgroundColor: C.green, borderWidth: 5, borderColor: C.bg, alignItems: 'center', justifyContent: 'center', shadowColor: C.dark, shadowOffset: { width: 0, height: 5 }, shadowOpacity: .25, shadowRadius: 8, elevation: 8 },
  createPressed: { transform: [{ scale: .94 }] },
  plus: { color: C.white, fontSize: 31, lineHeight: 34 },
  createLabel: { color: C.green, fontSize: 12, fontWeight: '900', marginTop: 3 },
  screenPad: { flex: 1, paddingHorizontal: 20, paddingTop: 18 },
  screenEyebrow: { color: C.green, fontSize: 12, letterSpacing: 1.7, fontWeight: '900', marginBottom: 5 },
  screenTitle: { color: C.ink, fontSize: 24, fontWeight: '800', letterSpacing: -.5, marginBottom: 20 },
  mapMock: { height: 430, borderRadius: 26, backgroundColor: '#E6EDDF', overflow: 'hidden', borderWidth: 1, borderColor: '#D3DDCE', position: 'relative' },
  road: { position: 'absolute', height: 30, backgroundColor: C.white, borderWidth: 1, borderColor: '#E2E7DE', width: '150%' },
  mapPin: { position: 'absolute', minWidth: 43, height: 34, paddingHorizontal: 8, borderRadius: 17, borderBottomLeftRadius: 5, backgroundColor: C.dark, alignItems: 'center', justifyContent: 'center', elevation: 5 },
  mapPinText: { color: C.white, fontSize: 12, fontWeight: '900' },
  youAreHere: { position: 'absolute', left: '48%', top: '47%', width: 34, height: 34, borderRadius: 17, backgroundColor: 'rgba(23,107,69,.22)', alignItems: 'center', justifyContent: 'center' },
  youDot: { width: 14, height: 14, borderRadius: 7, backgroundColor: C.green, borderWidth: 3, borderColor: C.white },
  mapInfo: { backgroundColor: C.white, borderRadius: 18, padding: 16, marginTop: 14, borderWidth: 1, borderColor: C.line },
  mapInfoTitle: { color: C.ink, fontSize: 15, fontWeight: '900' },
  mapInfoText: { color: C.muted, fontSize: 12, lineHeight: 18, marginTop: 4 },
  messageList: { backgroundColor: C.white, borderRadius: 22, paddingHorizontal: 15, borderWidth: 1, borderColor: C.line },
  messageRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 16 },
  rowLine: { borderBottomWidth: 1, borderBottomColor: C.line },
  messageAvatar: { width: 46, height: 46, borderRadius: 23, backgroundColor: C.soft, alignItems: 'center', justifyContent: 'center', marginRight: 12 },
  messageCopy: { flex: 1, paddingRight: 10 },
  messageName: { color: C.ink, fontSize: 14, fontWeight: '900', marginBottom: 4 },
  messagePreview: { color: C.muted, fontSize: 12 },
  messageTime: { color: C.muted, fontSize: 11, marginBottom: 7 },
  unread: { alignSelf: 'flex-end', width: 18, height: 18, borderRadius: 9, backgroundColor: C.green, alignItems: 'center', justifyContent: 'center' },
  unreadText: { color: C.white, fontSize: 11, fontWeight: '900' },
  profileCard: { backgroundColor: C.dark, borderRadius: 25, padding: 22, alignItems: 'center', marginBottom: 16 },
  profileAvatar: { width: 70, height: 70, borderRadius: 35, backgroundColor: C.lime, alignItems: 'center', justifyContent: 'center', marginBottom: 11 },
  profileAvatarText: { color: C.dark, fontSize: 28, fontWeight: '900' },
  profileName: { color: C.white, fontSize: 21, fontWeight: '900' },
  profileMeta: { color: '#B9CEC1', fontSize: 12, marginTop: 4 },
  stats: { width: '100%', flexDirection: 'row', alignItems: 'center', marginTop: 20, paddingTop: 18, borderTopWidth: 1, borderTopColor: '#416D57' },
  stat: { flex: 1, alignItems: 'center' },
  statValue: { color: C.white, fontSize: 18, fontWeight: '900' },
  statLabel: { color: '#B9CEC1', fontSize: 11, marginTop: 3 },
  statDivider: { width: 1, height: 30, backgroundColor: '#416D57' },
  menuRow: { height: 57, paddingHorizontal: 17, marginBottom: 9, borderRadius: 16, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, flexDirection: 'row', alignItems: 'center' },
  menuText: { color: C.ink, fontSize: 13, fontWeight: '800', flex: 1 },
  menuArrow: { color: C.muted, fontSize: 24 },
  successBackdrop: { flex: 1, backgroundColor: 'rgba(8,25,16,.66)', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 24 },
  successCard: { width: '100%', maxWidth: 390, borderRadius: 30, backgroundColor: C.white, padding: 24, alignItems: 'center', overflow: 'hidden', shadowColor: '#07160E', shadowOffset: { width: 0, height: 16 }, shadowOpacity: .28, shadowRadius: 28, elevation: 16 },
  successGlow: { position: 'absolute', width: 210, height: 210, borderRadius: 105, backgroundColor: '#E6F4D2', top: -125, right: -50 },
  successIcon: { width: 72, height: 72, borderRadius: 36, backgroundColor: C.green, borderWidth: 7, borderColor: '#E8F4E9', alignItems: 'center', justifyContent: 'center', marginTop: 2 },
  successIconText: { color: C.white, fontSize: 32, lineHeight: 36, fontWeight: '900' },
  successEyebrow: { color: C.green, fontSize: 12, letterSpacing: 1.8, fontWeight: '900', marginTop: 17 },
  successTitle: { color: C.ink, fontSize: 21, lineHeight: 27, fontWeight: '900', textAlign: 'center', letterSpacing: -.4, marginTop: 7 },
  successSummary: { width: '100%', borderRadius: 18, backgroundColor: '#F3F7F1', flexDirection: 'row', alignItems: 'center', marginTop: 20, paddingVertical: 15 },
  successSummaryItem: { flex: 1, alignItems: 'center' },
  successSummaryValue: { color: C.dark, fontSize: 16, fontWeight: '900' },
  successSummaryLabel: { color: C.muted, fontSize: 10, letterSpacing: .7, fontWeight: '900', marginTop: 3 },
  successSummaryDivider: { width: 1, height: 30, backgroundColor: '#D8E2D7' },
  successHint: { color: C.muted, fontSize: 12, lineHeight: 18, textAlign: 'center', marginTop: 12 },
  successPrimary: { width: '100%', height: 54, borderRadius: 17, backgroundColor: C.green, alignItems: 'center', justifyContent: 'center', marginTop: 18 },
  successPrimaryText: { color: C.white, fontSize: 13, fontWeight: '900' },
  successSecondary: { height: 44, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 20, marginTop: 3 },
  successSecondaryText: { color: C.green, fontSize: 12, fontWeight: '900' },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(10,24,16,.45)' },
  modalSheet: { maxHeight: '92%', backgroundColor: C.bg, borderTopLeftRadius: 30, borderTopRightRadius: 30, paddingHorizontal: 20, paddingTop: 10 },
  handle: { width: 42, height: 5, borderRadius: 3, backgroundColor: '#C8D0C9', alignSelf: 'center', marginBottom: 17 },
  modalHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 },
  modalTitle: { color: C.ink, fontSize: 23, fontWeight: '900', letterSpacing: -.6 },
  close: { width: 42, height: 42, borderRadius: 21, backgroundColor: C.white, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: C.line },
  closeText: { color: C.ink, fontSize: 28, lineHeight: 31 },
  formHint: { color: C.muted, fontSize: 12, lineHeight: 18, marginBottom: 13 },
  quantityRuleWarning: { marginTop: -3, marginBottom: 13, borderRadius: 13, borderWidth: 1, borderColor: '#E8B9B9', backgroundColor: '#FFF4F4', paddingHorizontal: 12, paddingVertical: 10 },
  quantityRuleWarningText: { color: '#A83A3A', fontSize: 12, lineHeight: 17, fontWeight: '800' },
  deliveryAddressCard: { minHeight: 78, borderRadius: 17, padding: 13, backgroundColor: C.white, borderWidth: 1, borderColor: '#B5D3BD', flexDirection: 'row', alignItems: 'center', marginBottom: 15 },
  deliveryAddressIcon: { width: 42, height: 42, borderRadius: 14, backgroundColor: C.soft, alignItems: 'center', justifyContent: 'center', marginRight: 11 },
  deliveryAddressIconText: { color: C.green, fontSize: 22, fontWeight: '900' },
  deliveryAddressCopy: { flex: 1, paddingRight: 6 },
  deliveryAddressTitleRow: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 7 },
  deliveryAddressTitle: { color: C.ink, fontSize: 13, fontWeight: '900' },
  deliveryDefaultBadge: { color: C.green, fontSize: 10, lineHeight: 14, fontWeight: '900', letterSpacing: .5, backgroundColor: C.soft, borderRadius: 7, paddingHorizontal: 6, paddingVertical: 3 },
  deliveryAddressText: { color: C.muted, fontSize: 12, lineHeight: 18, marginTop: 3 },
  materialFormCard: { borderRadius: 17, padding: 12, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, marginBottom: 10 },
  materialFormCardActive: { borderColor: '#B5D3BD', backgroundColor: '#FBFDFB' },
  materialFormHeader: { flexDirection: 'row', alignItems: 'center' },
  checkBox: { width: 24, height: 24, borderRadius: 8, borderWidth: 1.5, borderColor: '#BCC7BF', alignItems: 'center', justifyContent: 'center', marginRight: 9 },
  checkBoxActive: { backgroundColor: C.green, borderColor: C.green },
  checkMark: { color: C.white, fontSize: 14, fontWeight: '900' },
  materialFormName: { color: C.ink, fontSize: 14, fontWeight: '900', marginLeft: 9, flex: 1 },
  materialFormAction: { color: C.green, fontSize: 12, fontWeight: '800' },
  materialInputs: { flexDirection: 'row', gap: 10, marginTop: 12, paddingTop: 11, borderTopWidth: 1, borderTopColor: C.line },
  formHalf: { flex: 1 },
  inputLabel: { color: C.muted, fontSize: 12, fontWeight: '800', marginBottom: 6 },
  input: { minHeight: 48, borderRadius: 14, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, paddingHorizontal: 14, color: C.ink, fontSize: 16, fontWeight: '800' },
  invalidInput: { borderColor: '#C53D3D', borderWidth: 1.5 },
  validationText: { color: '#C53D3D', fontSize: 12, fontWeight: '700', marginTop: 5 },
  conditionCard: { marginBottom: 14, borderRadius: 17, borderWidth: 1, borderColor: '#D8E2DA', backgroundColor: C.white, padding: 14, flexDirection: 'row', alignItems: 'flex-start' },
  conditionCardChecked: { borderColor: '#78A98B', backgroundColor: '#F1F8F3' },
  conditionCheckbox: { width: 24, height: 24, borderRadius: 7, borderWidth: 1.5, borderColor: '#9AA79F', backgroundColor: C.white, alignItems: 'center', justifyContent: 'center', marginTop: 1 },
  conditionCheckboxChecked: { borderColor: C.green, backgroundColor: C.green },
  conditionCheck: { color: C.white, fontSize: 16, lineHeight: 18, fontWeight: '900' },
  conditionCopy: { flex: 1, marginLeft: 11 },
  conditionTitle: { color: C.ink, fontSize: 14, lineHeight: 19, fontWeight: '900' },
  conditionText: { color: '#516159', fontSize: 12, lineHeight: 18, marginTop: 4 },
  conditionHint: { color: '#956019', fontSize: 11, lineHeight: 16, fontWeight: '700', marginTop: 7 },
  inputSuffix: { minHeight: 48, borderRadius: 14, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, paddingHorizontal: 14, flexDirection: 'row', alignItems: 'center' },
  suffixInput: { flex: 1, color: C.ink, fontSize: 16, fontWeight: '800' },
  suffix: { color: C.muted, fontSize: 12, fontWeight: '800' },
  calculation: { marginTop: 6, borderRadius: 17, padding: 15, backgroundColor: C.soft, flexDirection: 'row', justifyContent: 'space-around', alignItems: 'center' },
  calcLabel: { color: C.green, fontSize: 10, marginBottom: 4, fontWeight: '800' },
  calcValue: { color: C.ink, fontSize: 16, fontWeight: '900' },
  calcGain: { color: C.green, fontSize: 16, fontWeight: '900' },
  calcDivider: { width: 1, height: 33, backgroundColor: '#C9DDCD' },
  primary: { height: 56, borderRadius: 17, backgroundColor: C.green, alignItems: 'center', justifyContent: 'center', marginTop: 13, marginBottom: 6 },
  primaryText: { color: C.white, fontSize: 14, fontWeight: '900' },
});
