import React, { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, AppState, Linking, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { C } from '../../styles';
import { ApiError, apiRequest } from '../lib/api';
import { useNotice } from '../notice/NoticeProvider';
import { enablePushNotifications, getPushNotificationState, PushNotificationState } from '../push/notifications';
import { NotificationPreferences } from './types';

const rows: { key: keyof NotificationPreferences; title: string; text: string }[] = [
  { key: 'messagesEnabled', title: 'Mesajlar', text: 'Yeni kullanıcı mesajları' },
  { key: 'pickupRequestsEnabled', title: 'Alım talepleri', text: 'Talep, kabul, ret ve iptal işlemleri' },
  { key: 'deliveryEnabled', title: 'Teslimatlar', text: 'Teslimat ve önemli işlem durumları' },
  { key: 'reviewsEnabled', title: 'Değerlendirmeler', text: 'Hatırlatmalar ve yeni puanlar' },
  { key: 'listingUpdatesEnabled', title: 'İlan güncellemeleri', text: 'İlan süresi ve favori durumları' },
  { key: 'marketingEnabled', title: 'Duyuru ve kampanyalar', text: 'İsteğe bağlı platform haberleri' },
];

export default function NotificationPreferencesScreen({ token, back }: { token: string; back: () => void }) {
  const { showNotice } = useNotice();
  const [preferences, setPreferences] = useState<NotificationPreferences | null>(null);
  const [pushState, setPushState] = useState<PushNotificationState>('checking');
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const refreshPush = useCallback(async (sync = false) => { const state = await getPushNotificationState(); setPushState(state); if (state === 'enabled' && sync) await enablePushNotifications(token); }, [token]);
  const load = useCallback(async () => { setLoading(true); try { setPreferences((await apiRequest<{ data: NotificationPreferences }>('/notification-preferences', { token })).data); } catch (error) { showNotice({ tone: 'error', title: 'Tercihler alınamadı', message: error instanceof ApiError ? error.message : 'Sunucuya ulaşılamadı.' }); } finally { setLoading(false); } }, [showNotice, token]);
  useEffect(() => { void load(); void refreshPush(true); const subscription = AppState.addEventListener('change', state => { if (state === 'active') void refreshPush(true); }); return () => subscription.remove(); }, [load, refreshPush]);
  const enablePush = async () => { if (pushState === 'blocked') return void Linking.openSettings(); setPushState('checking'); const result = await enablePushNotifications(token); await refreshPush(result.ok); showNotice(result.ok ? { tone: 'success', title: 'Bildirimler açıldı', message: 'Bildirimler bu telefona gönderilebilir.' } : { tone: 'warning', title: 'Bildirimler açılamadı', message: result.message }); };
  const pushInfo = { checking: ['Kontrol ediliyor', 'Bildirim durumu kontrol ediliyor'], expo_go: ['Development build gerekli', 'Expo Go uzaktan bildirim desteklemez'], physical_device_required: ['Fiziksel telefon gerekli', 'Simülatörde uzaktan bildirim açılamaz'], not_configured: ['Kurulum tamamlanmadı', 'FCM/APNs yapılandırması gerekiyor'], disabled: ['Bildirimleri aç', 'Telefon bildirimlerine izin ver'], blocked: ['Telefon ayarlarından aç', 'Bildirim izni daha önce engellenmiş'], enabled: ['Bildirimler açık', 'Bu telefon bildirim alabilir'] }[pushState];
  const actionable = pushState === 'disabled' || pushState === 'blocked';
  const save = async () => { if (!preferences || saving) return; setSaving(true); try { setPreferences((await apiRequest<{ data: NotificationPreferences }>('/notification-preferences', { method: 'PATCH', token, body: preferences })).data); showNotice({ tone: 'success', title: 'Tercihler kaydedildi', message: 'Bildirimler seçtiğin kategorilere göre gönderilecek.' }); back(); } catch (error) { showNotice({ tone: 'error', title: 'Tercihler kaydedilemedi', message: error instanceof ApiError ? error.message : 'Sunucuya ulaşılamadı.' }); } finally { setSaving(false); } };
  return <View style={x.screen}><View style={x.header}><Pressable onPress={back} style={x.back}><Text style={x.backText}>‹</Text></Pressable><View><Text style={x.eyebrow}>TELEFON BİLDİRİMLERİ</Text><Text style={x.title}>Bildirim tercihleri</Text></View></View>{loading || !preferences ? <View style={x.loading}><ActivityIndicator color={C.green} /></View> : <ScrollView contentContainerStyle={x.content}><Pressable disabled={!actionable} onPress={() => void enablePush()} style={x.pushCard}><View style={[x.pushDot, pushState === 'enabled' && x.pushDotEnabled]} /><View style={x.pushCopy}><Text style={x.pushTitle}>{pushInfo[0]}</Text><Text style={x.pushText}>{pushInfo[1]}</Text></View>{actionable && <Text style={x.arrow}>›</Text>}</Pressable><Text style={x.intro}>Uygulama içindeki işlem geçmişi görünmeye devam eder. Burada telefonuna gönderilecek kategorileri yönetebilirsin.</Text>{rows.map(row => <View key={row.key} style={x.row}><View style={x.rowCopy}><Text style={x.rowTitle}>{row.title}</Text><Text style={x.rowText}>{row.text}</Text></View><Switch accessibilityLabel={`${row.title} bildirimleri`} value={preferences[row.key]} onValueChange={value => setPreferences(current => current ? { ...current, [row.key]: value } : current)} trackColor={{ false: '#CFD7D1', true: '#8FC7A4' }} thumbColor={preferences[row.key] ? C.green : '#F4F4F4'} /></View>)}<Pressable disabled={saving} onPress={() => void save()} style={[x.save, saving && x.disabled]}>{saving ? <ActivityIndicator color={C.white} /> : <Text style={x.saveText}>Tercihleri kaydet</Text>}</Pressable></ScrollView>}</View>;
}

const x = StyleSheet.create({ screen: { flex: 1, backgroundColor: C.bg }, header: { minHeight: 76, paddingHorizontal: 16, flexDirection: 'row', alignItems: 'center', backgroundColor: C.white, borderBottomWidth: 1, borderBottomColor: C.line }, back: { width: 44, height: 44, borderRadius: 22, alignItems: 'center', justifyContent: 'center', backgroundColor: C.bg, marginRight: 11 }, backText: { color: C.ink, fontSize: 30, lineHeight: 33 }, eyebrow: { color: C.green, fontSize: 11, letterSpacing: 1.3, fontWeight: '900' }, title: { color: C.ink, fontSize: 20, fontWeight: '900', marginTop: 2 }, loading: { flex: 1, alignItems: 'center', justifyContent: 'center' }, content: { padding: 18, paddingBottom: 30 }, pushCard: { minHeight: 72, borderRadius: 18, backgroundColor: C.dark, padding: 14, flexDirection: 'row', alignItems: 'center', marginBottom: 14 }, pushDot: { width: 13, height: 13, borderRadius: 7, backgroundColor: '#D8A448', marginRight: 12 }, pushDotEnabled: { backgroundColor: C.lime }, pushCopy: { flex: 1 }, pushTitle: { color: C.white, fontSize: 13, fontWeight: '900' }, pushText: { color: '#B9CEC1', fontSize: 12, lineHeight: 18, marginTop: 3 }, arrow: { color: C.lime, fontSize: 24 }, intro: { color: C.muted, fontSize: 12, lineHeight: 18, marginBottom: 13 }, row: { minHeight: 69, padding: 13, marginBottom: 8, borderRadius: 17, backgroundColor: C.white, borderWidth: 1, borderColor: C.line, flexDirection: 'row', alignItems: 'center' }, rowCopy: { flex: 1, paddingRight: 10 }, rowTitle: { color: C.ink, fontSize: 13, fontWeight: '900' }, rowText: { color: C.muted, fontSize: 11, lineHeight: 16, marginTop: 3 }, save: { height: 55, borderRadius: 17, backgroundColor: C.green, alignItems: 'center', justifyContent: 'center', marginTop: 8 }, disabled: { opacity: .7 }, saveText: { color: C.white, fontSize: 13, fontWeight: '900' } });
