@extends('layouts.marketing')
@section('title', 'Hesap silme')
@section('description', 'Döngü hesabınızı ve kişisel verilerinizi silme talebi oluşturun.')
@section('content')
<section class="vision-legal"><div class="site-shell"><header class="vision-legal-hero"><span class="vision-legal-kicker">HESAP VE VERİ KONTROLÜ</span><h1>Döngü hesabını sil</h1><p class="vision-legal-summary">Uygulamadaki Profil → Hesabımı sil bölümünü kullanabilir veya uygulamaya erişemiyorsanız bu sayfadan e-posta doğrulaması yapabilirsiniz.</p></header><div class="vision-legal-layout"><aside class="vision-legal-toc"><strong>İŞLEM ÖZETİ</strong><a href="#silinenler">Silinen veriler</a><a href="#dogrulama">E-posta doğrulama</a><a href="{{ route('legal.privacy') }}">Gizlilik politikası</a></aside><article class="vision-legal-content">
    <section class="vision-legal-section" id="silinenler"><h2>Silme işleminden önce</h2><div class="vision-delete-box"><strong>Silinen veriler</strong><ul><li>Ad, e-posta, telefon, avatar ve kayıtlı adresler</li><li>Aktif ilanlar ve kesin teslimat konumları</li><li>Bildirilmeyen mesaj içerikleri ve kişisel yorumlar</li></ul><strong>Anonim saklanabilen kayıtlar</strong><p>Tamamlanmış teslimat, güvenlik, ihlal ve denetim kayıtları; hukuki yükümlülükler ve kötüye kullanımı önlemek için kimlikten arındırılarak korunabilir.</p></div></section>
    <section class="vision-legal-section" id="dogrulama"><h2>E-posta ile doğrula</h2>@if($errors->any())<div class="vision-alert">{{ $errors->first() }}</div>@endif @if(session('code_sent'))<div class="vision-alert success">Bu adres aktif bir Döngü hesabına aitse 6 haneli kod gönderildi.</div><form class="vision-delete-form" method="post" action="{{ route('account-deletion.destroy') }}">@csrf<label>E-posta</label><input name="email" type="email" value="{{ old('email') }}" required><label>Doğrulama kodu</label><input name="code" type="text" inputmode="numeric" maxlength="6" required><div class="vision-delete-check"><input id="confirmation" name="confirmation" type="checkbox" value="1" required><label for="confirmation">İşlemin geri alınamayacağını ve hesabımın silineceğini anlıyorum.</label></div><button>Hesabımı ve verilerimi sil</button></form>@else<form class="vision-delete-form" method="post" action="{{ route('account-deletion.code') }}">@csrf<label>Hesabındaki e-posta</label><input name="email" type="email" value="{{ old('email') }}" required><button>Doğrulama kodu gönder</button></form>@endif</section>
    <aside class="vision-legal-contact">Yardıma mı ihtiyacınız var? <a href="mailto:yalovawebcozumleri@gmail.com">yalovawebcozumleri@gmail.com</a></aside>
</article></div></div></section>
@endsection
