<script setup>
import AdminLayout from '../../Layouts/AdminLayout.vue';
import { Head, Link } from '@inertiajs/vue3';

defineProps({ stats: Object, listingStatusCounts: Object, listings: Array });
const materials = { pet: 'PET', glass: 'Cam', aluminum: 'Alüminyum' };
const statuses = { active: 'Aktif', reserved: 'Rezerve', completed: 'Tamamlandı', cancelled: 'İptal' };
const statusClasses = { active: 'bg-emerald-50 text-emerald-800', reserved: 'bg-amber-50 text-amber-800', completed: 'bg-sky-50 text-sky-800', cancelled: 'bg-slate-100 text-slate-700' };
</script>

<template>
  <Head title="Genel Bakış" />
  <AdminLayout eyebrow="Genel Bakış" title="Pazaryeri durumu" description="Kullanıcıları, ilanları ve platformdaki güncel hareketleri tek ekrandan takip et.">
    <main class="mx-auto max-w-[1600px] px-5 py-8 lg:px-8">
      <section class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <Link href="/admin/users" class="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-emerald-300 hover:shadow-md"><div class="flex items-start justify-between gap-3"><div><p class="text-sm font-semibold text-slate-700">Kullanıcılar</p><p class="mt-3 text-3xl font-semibold tracking-tight text-slate-950">{{ stats.users.toLocaleString('tr-TR') }}</p><p class="mt-1 text-sm text-slate-600">Kayıtlı hesapları yönet</p></div><span class="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><svg viewBox="0 0 24 24" class="size-5" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M16 20v-1.5a4 4 0 0 0-4-4H7a4 4 0 0 0-4 4V20M9.5 10.5a3.5 3.5 0 1 0 0-7 3.5 3.5 0 0 0 0 7ZM17 8h4m-2-2v4"/></svg></span></div><p class="mt-4 text-xs font-semibold text-emerald-700">Kullanıcı yönetimine git →</p></Link>
        <Link href="/admin/listings?status=active" class="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-emerald-300 hover:shadow-md"><div class="flex items-start justify-between gap-3"><div><p class="text-sm font-semibold text-slate-700">Aktif ilanlar</p><p class="mt-3 text-3xl font-semibold tracking-tight text-slate-950">{{ stats.activeListings.toLocaleString('tr-TR') }}</p><p class="mt-1 text-sm text-slate-600">Yayındaki ilanları yönet</p></div><span class="grid size-10 place-items-center rounded-xl bg-sky-50 text-sky-700"><svg viewBox="0 0 24 24" class="size-5" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M6 3h9l3 3v15H6zM9 11h6m-6 4h6M14 3v4h4"/></svg></span></div><p class="mt-4 text-xs font-semibold text-emerald-700">İlan yönetimine git →</p></Link>
        <Link href="/admin/listings?status=completed" class="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-emerald-300 hover:shadow-md"><div class="flex items-start justify-between gap-3"><div><p class="text-sm font-semibold text-slate-700">Tamamlanan teslimatlar</p><p class="mt-3 text-3xl font-semibold tracking-tight text-slate-950">{{ stats.completedTransactions.toLocaleString('tr-TR') }}</p><p class="mt-1 text-sm text-slate-600">Alıcı ve satıcı işlemleri</p></div><span class="grid size-10 place-items-center rounded-xl bg-violet-50 text-violet-700"><svg viewBox="0 0 24 24" class="size-5" fill="none" stroke="currentColor" stroke-width="1.8"><path d="m5 12 4 4L19 6M4 21h16"/></svg></span></div><p class="mt-4 text-xs font-semibold text-emerald-700">Tamamlananları incele →</p></Link>
        <Link href="/admin/listings" class="group rounded-2xl border border-slate-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-emerald-300 hover:shadow-md"><div class="flex items-start justify-between gap-3"><div><p class="text-sm font-semibold text-slate-700">Toplam ambalaj</p><p class="mt-3 text-3xl font-semibold tracking-tight text-slate-950">{{ stats.materials.toLocaleString('tr-TR') }}</p><p class="mt-1 text-sm text-slate-600">İlanlardaki toplam adet</p></div><span class="grid size-10 place-items-center rounded-xl bg-amber-50 text-amber-700"><svg viewBox="0 0 24 24" class="size-5" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M7 4h10v4l2 3v9H5v-9l2-3zM7 8h10M9 13h6"/></svg></span></div><p class="mt-4 text-xs font-semibold text-emerald-700">İlanlarda görüntüle →</p></Link>
      </section>

      <section class="mt-6 grid gap-5 lg:grid-cols-[1fr_320px]">
        <article class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-200 px-5 py-4"><div><h2 class="text-lg font-semibold text-slate-950">Son ilanlar</h2><p class="mt-1 text-sm text-slate-600">En son oluşturulan 10 kayıt</p></div><Link href="/admin/listings" class="rounded-xl border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-800 hover:border-emerald-500 hover:text-emerald-700">Tüm ilanları yönet</Link></div><div v-if="listings.length" class="overflow-x-auto"><table class="w-full min-w-[900px] text-left text-sm"><thead class="border-b border-slate-200 bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-700"><tr><th class="px-5 py-3.5">İlan</th><th class="px-5 py-3.5">Satıcı / Alıcı</th><th class="px-5 py-3.5">Malzemeler</th><th class="px-5 py-3.5">Bölge</th><th class="px-5 py-3.5">Durum</th><th class="px-5 py-3.5 text-right">İşlem</th></tr></thead><tbody class="divide-y divide-slate-100"><tr v-for="listing in listings" :key="listing.id" class="text-slate-800 hover:bg-slate-50"><td class="px-5 py-4 font-semibold text-slate-950">#{{ listing.id }}</td><td class="px-5 py-4"><p class="font-semibold text-slate-950">{{ listing.seller?.name }}</p><p class="text-xs text-slate-600">Satıcı</p><template v-if="listing.buyer"><p class="mt-2 font-semibold text-slate-950">{{ listing.buyer.name }}</p><p class="text-xs text-slate-600">Alıcı</p></template></td><td class="px-5 py-4"><div class="flex flex-wrap gap-1"><span v-for="item in listing.materials" :key="item.type" class="rounded-lg bg-cream-100 px-2 py-1 text-xs font-semibold text-forest-900">{{ materials[item.type] }} · {{ item.quantity }}</span></div></td><td class="px-5 py-4 font-medium">{{ listing.public_area }}</td><td class="px-5 py-4"><span :class="['rounded-full px-2.5 py-1 text-xs font-semibold', statusClasses[listing.status]]">{{ statuses[listing.status] }}</span></td><td class="px-5 py-4 text-right"><Link :href="`/admin/listings/${listing.id}`" title="İlanı görüntüle" class="inline-grid size-9 place-items-center rounded-lg border border-slate-300 text-slate-700 hover:border-emerald-500 hover:text-emerald-700"><svg viewBox="0 0 24 24" class="size-4" fill="none" stroke="currentColor" stroke-width="1.8"><path d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6Z"/><circle cx="12" cy="12" r="2.5"/></svg></Link></td></tr></tbody></table></div><div v-else class="px-5 py-14 text-center text-sm font-semibold text-slate-700">Henüz ilan bulunmuyor.</div></article>
        <aside class="space-y-5"><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-semibold text-slate-950">İlan dağılımı</h2><div class="mt-4 space-y-3"><Link v-for="item in [['active','Aktif',listingStatusCounts.active],['reserved','Rezerve',listingStatusCounts.reserved],['completed','Tamamlandı',listingStatusCounts.completed],['cancelled','İptal',listingStatusCounts.cancelled]]" :key="item[0]" :href="`/admin/listings?status=${item[0]}`" class="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3"><span class="text-sm font-semibold text-slate-800">{{ item[1] }}</span><span class="text-sm font-semibold text-slate-950">{{ item[2] }}</span></Link></div></section><section class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-semibold text-slate-950">Bekleyen işler</h2><div class="mt-4 space-y-3"><Link href="/admin/message-reports" class="flex w-full items-center justify-between rounded-xl bg-red-50 px-4 py-3 text-left"><span class="text-sm font-semibold text-red-900">Güvenlik incelemeleri</span><span class="text-sm font-semibold text-red-800">{{ stats.pendingModeration }}</span></Link><Link href="/admin/announcements" class="flex items-center justify-between rounded-xl bg-slate-50 px-4 py-3"><span class="text-sm font-semibold text-slate-800">Planlı duyurular</span><span class="text-sm font-semibold text-slate-950">{{ stats.scheduledAnnouncements }}</span></Link></div></section></aside>
      </section>
    </main>
  </AdminLayout>
</template>
