@extends('layouts.marketing')
@section('title', 'Döngü Destekçileri')
@section('description', 'İşletmenizi bölgenizdeki Döngü kullanıcılarına tanıtın; gösterim ve yönlendirme performansınızı kendi panelinizden izleyin.')
@section('content')
<section class="site-page-hero"><div class="site-shell site-page-hero-inner"><span class="site-kicker"><i></i> DÖNGÜ DESTEKÇİLERİ</span><h1>İşletmeniz, doğru<br>bölgede görünür olsun.</h1><p>Döngü Destekçisi olarak bulunduğunuz il veya ilçedeki kullanıcılara ulaşın. Karmaşık reklam panelleri yerine anlaşılır bir profil, tek yönlendirme ve şeffaf istatistikler.</p><div class="site-hero-actions"><a class="site-button site-button-lime" href="https://wa.me/905413342219?text=Merhaba%2C%20D%C3%B6ng%C3%BC%20Destek%C3%A7isi%20olmak%20hakk%C4%B1nda%20bilgi%20almak%20istiyorum." target="_blank" rel="noopener">WhatsApp'tan bilgi al <span>↗</span></a></div></div></section>
<section class="site-content-section"><div class="site-shell"><div class="site-section-heading"><span class="site-eyebrow">SADE VE ÖLÇÜLEBİLİR</span><h2>Bir profil.<br>Gerçek bölgesel görünürlük.</h2><p>Kullanıcılar bölgesindeki destekçileri keşfeder, işletme profilinizi inceler ve belirlediğiniz tek ana aksiyon üzerinden size ulaşır.</p></div><div class="site-supporter-benefits"><article><strong>01</strong><h3>Bölge hedefleme</h3><p>İşletmeniz yalnızca hizmet verdiğiniz il veya ilçedeki kullanıcılara gösterilir.</p></article><article><strong>02</strong><h3>Net yönlendirme</h3><p>WhatsApp, telefon veya web sitesi seçeneklerinden işletmeniz için en doğru olanı kullanın.</p></article><article><strong>03</strong><h3>Kendi paneliniz</h3><p>Günlük görüntülenme ve yönlendirme sayılarını kişisel destekçi panelinizden izleyin.</p></article></div></div></section>
<section class="site-content-section site-materials"><div class="site-shell site-content-grid"><div><span class="site-eyebrow">PROFİLİNİZDE</span><h2>Kullanıcının karar vermesi için gereken kadar bilgi.</h2></div><div class="site-content-prose"><p>İşletme adı, logo, kısa tanıtım, kategori, hizmet bölgesi ve iletişim yönlendirmesi. Gereksiz kalabalık olmadan markanızı anlatan temiz bir profil.</p><p>Profiliniz uygulamadaki Döngü Destekçileri alanında listelenir. Kullanıcı detay sayfanıza geçtiğinde işletmenizi tanır ve seçtiğiniz aksiyonla size ulaşır.</p><p>Her destekçi hesabı yönetici tarafından oluşturulur ve yayın öncesinde kontrol edilir. Böylece kullanıcıların gördüğü içerik düzenli ve güvenilir kalır.</p></div></div></section>
<section class="site-content-section"><div class="site-shell"><div class="site-whatsapp-panel"><div><span class="site-eyebrow">İLK ADIM</span><h2>Bölgenizde Döngü'yü birlikte büyütelim.</h2><p>İşletmenizin konumunu ve iletişim tercihini konuşalım; size uygun destekçi görünümünü birlikte oluşturalım.</p></div><a class="site-button site-button-dark" href="https://wa.me/905413342219?text=Merhaba%2C%20D%C3%B6ng%C3%BC%20Destek%C3%A7isi%20olmak%20hakk%C4%B1nda%20bilgi%20almak%20istiyorum." target="_blank" rel="noopener">+90 541 334 22 19 <span>↗</span></a></div></div></section>
@endsection
