<script setup>
import AdminLayout from '../../../Layouts/AdminLayout.vue';
import { Head, router, useForm } from '@inertiajs/vue3';
import { computed, ref } from 'vue';

const props = defineProps({ supporters: Array, scopeOptions: Array, ctaOptions: Array });
const modalOpen = ref(false); const editing = ref(null); const deleteTarget = ref(null);
const blank = () => ({ name: '', cardSummary: '', detailTitle: '', detailBody: '', targetScope: 'district', provinceCode: '', provinceName: '', districtCode: '', districtName: '', ctaType: 'whatsapp', ctaLabel: 'İletişime geç', ctaValue: '', priority: 0, startsAt: '', endsAt: '', isActive: false, logo: null, accountName: '', accountEmail: '', accountPassword: '' });
const form = useForm(blank());
const openCreate = () => { editing.value = null; form.defaults(blank()); form.reset(); form.clearErrors(); modalOpen.value = true; };
const openEdit = item => { editing.value = item; form.defaults({ ...blank(), ...item, accountPassword: '', logo: null }); form.reset(); form.clearErrors(); modalOpen.value = true; };
const close = () => { if (!form.processing) modalOpen.value = false; };
const submit = () => {
  const options = { preserveScroll: true, forceFormData: true, onSuccess: () => { modalOpen.value = false; form.reset(); } };
  if (editing.value) form.transform(data => ({ ...data, _method: 'patch' })).post(`/admin/supporters/${editing.value.id}`, options);
  else form.transform(data => data).post('/admin/supporters', options);
};
const remove = () => router.delete(`/admin/supporters/${deleteTarget.value.id}`, { preserveScroll: true, onSuccess: () => deleteTarget.value = null });
const scopeLabel = item => item.targetScope === 'district' ? `${item.districtName}, ${item.provinceName}` : item.targetScope === 'province' ? `${item.provinceName} geneli` : 'Türkiye geneli';
const ctr = item => item.totals.impressions ? `%${(item.totals.ctaClicks / item.totals.impressions * 100).toFixed(1).replace('.', ',')}` : '%0';
const title = computed(() => editing.value ? 'Destekçiyi düzenle' : 'Yeni destekçi oluştur');
</script>

<template>
  <Head title="Döngü Destekçileri" />
  <AdminLayout eyebrow="Gelir" title="Döngü Destekçileri" description="İşletmeleri, bölgesel yayınlarını, yönlendirmelerini ve performans hesaplarını tek yerden yönet.">
    <main class="mx-auto max-w-[1600px] px-5 py-8 lg:px-8">
      <div class="mb-5 flex flex-wrap items-center justify-between gap-4"><div><h2 class="text-xl font-semibold tracking-[-.02em]">Destekçi işletmeler</h2><p class="mt-1 text-sm text-slate-600">{{ supporters.length }} kayıtlı işletme</p></div><button class="min-h-11 rounded-xl bg-emerald-700 px-5 text-sm font-semibold text-white hover:bg-emerald-800" @click="openCreate">+ Yeni destekçi</button></div>
      <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
        <div class="overflow-x-auto"><table class="w-full min-w-[1050px] text-left"><thead class="border-b border-slate-200 bg-slate-50"><tr><th class="px-5 py-3.5 text-xs font-semibold text-slate-700">İşletme</th><th class="px-5 py-3.5 text-xs font-semibold text-slate-700">Hedef bölge</th><th class="px-5 py-3.5 text-xs font-semibold text-slate-700">Yayın</th><th class="px-5 py-3.5 text-xs font-semibold text-slate-700">Bugün</th><th class="px-5 py-3.5 text-xs font-semibold text-slate-700">Toplam performans</th><th class="px-5 py-3.5 text-right text-xs font-semibold text-slate-700">İşlemler</th></tr></thead>
          <tbody class="divide-y divide-slate-100"><tr v-for="item in supporters" :key="item.id" class="hover:bg-slate-50/70"><td class="px-5 py-4"><div class="flex items-center gap-3"><img v-if="item.logoUrl" :src="item.logoUrl" class="h-11 w-11 rounded-xl object-cover" /><div v-else class="flex h-11 w-11 items-center justify-center rounded-xl bg-emerald-100 text-sm font-semibold text-emerald-800">{{ item.name.slice(0, 2).toUpperCase() }}</div><div><p class="font-semibold text-slate-950">{{ item.name }}</p><p class="mt-0.5 text-xs text-slate-600">{{ item.accountEmail }}</p></div></div></td><td class="px-5 py-4"><p class="text-sm font-semibold">{{ scopeLabel(item) }}</p><p class="mt-0.5 text-xs text-slate-500">Öncelik {{ item.priority }}</p></td><td class="px-5 py-4"><span :class="['rounded-full px-2.5 py-1 text-xs font-semibold', item.isActive ? 'bg-emerald-100 text-emerald-800' : 'bg-slate-100 text-slate-600']">{{ item.isActive ? 'Aktif' : 'Pasif' }}</span></td><td class="px-5 py-4 text-sm"><b>{{ item.today.impressions.toLocaleString('tr-TR') }}</b> gösterim<br><span class="text-xs text-slate-500">{{ item.today.uniqueReach.toLocaleString('tr-TR') }} tekil</span></td><td class="px-5 py-4 text-sm"><b>{{ item.totals.impressions.toLocaleString('tr-TR') }}</b> gösterim · <b>{{ item.totals.ctaClicks.toLocaleString('tr-TR') }}</b> tıklama<br><span class="text-xs text-slate-500">CTR {{ ctr(item) }}</span></td><td class="px-5 py-4"><div class="flex justify-end gap-2"><button class="rounded-lg border border-slate-200 px-3 py-2 text-xs font-semibold hover:bg-slate-50" @click="openEdit(item)">Düzenle</button><button class="rounded-lg border border-red-200 px-3 py-2 text-xs font-semibold text-red-700 hover:bg-red-50" @click="deleteTarget = item">Kaldır</button></div></td></tr><tr v-if="!supporters.length"><td colspan="6" class="px-5 py-16 text-center text-sm text-slate-600">Henüz destekçi işletme oluşturulmadı.</td></tr></tbody>
        </table></div>
      </section>
    </main>

    <div v-if="modalOpen" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4" @mousedown.self="close"><section class="max-h-[92vh] w-full max-w-3xl overflow-y-auto rounded-3xl bg-white shadow-2xl"><header class="sticky top-0 z-10 flex items-center justify-between border-b border-slate-200 bg-white px-6 py-5"><div><p class="text-[11px] font-semibold uppercase tracking-[.14em] text-emerald-700">Döngü Destekçisi</p><h2 class="mt-1 text-xl font-semibold">{{ title }}</h2></div><button class="h-10 w-10 rounded-xl bg-slate-100 text-xl" @click="close">×</button></header>
      <form class="space-y-6 p-6" @submit.prevent="submit">
        <fieldset class="grid gap-4 sm:grid-cols-2"><legend class="col-span-full mb-3 text-sm font-semibold">İşletme ve içerik</legend><label class="block text-xs font-semibold">İşletme adı *<input v-model="form.name" required maxlength="120" class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label><label class="block text-xs font-semibold">Logo<input type="file" accept="image/jpeg,image/png,image/webp" class="mt-1.5 block w-full text-xs" @input="form.logo = $event.target.files[0]" /></label><label class="col-span-full block text-xs font-semibold">Kart açıklaması *<input v-model="form.cardSummary" required maxlength="180" class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label><label class="col-span-full block text-xs font-semibold">Detay başlığı *<input v-model="form.detailTitle" required maxlength="160" class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label><label class="col-span-full block text-xs font-semibold">Detay metni *<textarea v-model="form.detailBody" required maxlength="3000" rows="5" class="mt-1.5 w-full rounded-xl border border-slate-200 p-3 text-sm" /></label></fieldset>
        <fieldset class="grid gap-4 sm:grid-cols-2"><legend class="col-span-full mb-3 text-sm font-semibold">Bölge ve yayın</legend><label class="block text-xs font-semibold">Hedef alan *<select v-model="form.targetScope" class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"><option v-for="option in scopeOptions" :key="option.value" :value="option.value">{{ option.label }}</option></select></label><label class="block text-xs font-semibold">Öncelik *<input v-model.number="form.priority" type="number" min="0" max="1000" class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label><template v-if="form.targetScope !== 'nationwide'"><label class="block text-xs font-semibold">İl adı *<input v-model="form.provinceName" required placeholder="Yalova" class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label><label class="block text-xs font-semibold">İl kodu *<input v-model="form.provinceCode" required placeholder="77" class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label></template><template v-if="form.targetScope === 'district'"><label class="block text-xs font-semibold">İlçe adı *<input v-model="form.districtName" required placeholder="Çınarcık" class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label><label class="block text-xs font-semibold">İlçe kodu *<input v-model="form.districtCode" required placeholder="77-02" class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label></template><label class="block text-xs font-semibold">Başlangıç<input v-model="form.startsAt" type="datetime-local" class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label><label class="block text-xs font-semibold">Bitiş<input v-model="form.endsAt" type="datetime-local" class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label><label class="col-span-full flex items-center gap-2 text-sm font-semibold"><input v-model="form.isActive" type="checkbox" /> Kaydeder kaydetmez yayına al</label></fieldset>
        <fieldset class="grid gap-4 sm:grid-cols-3"><legend class="col-span-full mb-3 text-sm font-semibold">Yönlendirme</legend><label class="block text-xs font-semibold">Tür *<select v-model="form.ctaType" class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm"><option v-for="option in ctaOptions" :key="option.value" :value="option.value">{{ option.label }}</option></select></label><label class="block text-xs font-semibold">Buton metni *<input v-model="form.ctaLabel" required class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label><label class="block text-xs font-semibold">Bağlantı / telefon *<input v-model="form.ctaValue" required class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label></fieldset>
        <fieldset class="grid gap-4 sm:grid-cols-2"><legend class="col-span-full mb-3 text-sm font-semibold">İşletme panel hesabı</legend><label class="block text-xs font-semibold">Yetkili adı *<input v-model="form.accountName" required class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label><label class="block text-xs font-semibold">E-posta *<input v-model="form.accountEmail" type="email" required class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label><label class="col-span-full block text-xs font-semibold">{{ editing ? 'Yeni şifre (değişmeyecekse boş bırak)' : 'Panel şifresi *' }}<input v-model="form.accountPassword" type="password" :required="!editing" minlength="8" class="mt-1.5 min-h-11 w-full rounded-xl border border-slate-200 px-3 text-sm" /></label></fieldset>
        <div v-if="Object.keys(form.errors).length" class="rounded-xl bg-red-50 p-4 text-sm text-red-700"><p v-for="(error, key) in form.errors" :key="key">{{ error }}</p></div>
        <div class="flex justify-end gap-3 border-t border-slate-100 pt-5"><button type="button" class="min-h-11 rounded-xl border border-slate-200 px-5 text-sm font-semibold" @click="close">Vazgeç</button><button :disabled="form.processing" class="min-h-11 rounded-xl bg-emerald-700 px-6 text-sm font-semibold text-white disabled:opacity-50">{{ editing ? 'Değişiklikleri kaydet' : 'Destekçiyi oluştur' }}</button></div>
      </form></section></div>
    <div v-if="deleteTarget" class="fixed inset-0 z-50 flex items-center justify-center bg-slate-950/45 p-4"><section class="w-full max-w-md rounded-3xl bg-white p-6 shadow-2xl"><h2 class="text-xl font-semibold">Destekçi yayından kaldırılsın mı?</h2><p class="mt-3 text-sm leading-6 text-slate-600"><b>{{ deleteTarget.name }}</b> mobil uygulamadan kaldırılacak ve panel hesabı askıya alınacak. Geçmiş istatistikler denetim için korunur.</p><div class="mt-6 flex justify-end gap-3"><button class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold" @click="deleteTarget = null">Vazgeç</button><button class="rounded-xl bg-red-700 px-4 py-2.5 text-sm font-semibold text-white" @click="remove">Yayından kaldır</button></div></section></div>
  </AdminLayout>
</template>
