import { StyleSheet } from 'react-native';

export const authColors = {
  ink: '#13251B',
  muted: '#66756D',
  green: '#176B45',
  greenDark: '#0F5436',
  soft: '#EDF5EE',
  line: '#DCE5DE',
  white: '#FFFFFF',
  danger: '#B83A3A',
};

export const authStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: '#F7F9F6' },
  keyboard: { flex: 1 },
  scroll: { flex: 1 },
  page: { flexGrow: 1, paddingHorizontal: 24, paddingTop: 22, paddingBottom: 32 },
  loading: { flex: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#0D4E32' },
  loadingLogo: { color: authColors.ink, fontSize: 34, fontWeight: '900', letterSpacing: -1.5, marginBottom: 18 },
  logoDot: { color: authColors.green },
  topRow: { minHeight: 46, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  brand: { color: authColors.ink, fontSize: 26, fontWeight: '900', letterSpacing: -1 },
  back: { width: 42, height: 42, borderRadius: 14, borderWidth: 1, borderColor: authColors.line, backgroundColor: authColors.white, alignItems: 'center', justifyContent: 'center' },
  backText: { color: authColors.ink, fontSize: 27, lineHeight: 29, fontWeight: '700' },
  hero: { marginTop: 34, padding: 23, borderRadius: 28, backgroundColor: authColors.green, overflow: 'hidden' },
  heroBadge: { alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 10, backgroundColor: 'rgba(255,255,255,.16)' },
  heroBadgeText: { color: authColors.white, fontSize: 12, fontWeight: '900', letterSpacing: .8 },
  heroTitle: { color: authColors.white, fontSize: 33, lineHeight: 38, fontWeight: '900', letterSpacing: -1.2, marginTop: 20 },
  heroText: { color: '#D8EDDF', fontSize: 14, lineHeight: 21, fontWeight: '600', marginTop: 12, maxWidth: 300 },
  stats: { flexDirection: 'row', gap: 8, marginTop: 20 },
  stat: { flex: 1, padding: 11, borderRadius: 15, backgroundColor: 'rgba(255,255,255,.12)' },
  statValue: { color: authColors.white, fontSize: 16, fontWeight: '900' },
  statLabel: { color: '#D8EDDF', fontSize: 11, fontWeight: '700', marginTop: 3 },
  content: { marginTop: 34 },
  authHero: { position: 'relative', overflow: 'hidden', marginTop: 25, minHeight: 238, padding: 21, borderRadius: 28, backgroundColor: authColors.greenDark },
  authHeroGlowLarge: { position: 'absolute', width: 190, height: 190, borderRadius: 95, right: -72, top: -78, backgroundColor: '#2D7957', opacity: .72 },
  authHeroGlowSmall: { position: 'absolute', width: 105, height: 105, borderRadius: 53, left: -49, bottom: -54, backgroundColor: '#2A704F', opacity: .62 },
  authHeroTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  authStepPill: { borderRadius: 10, paddingHorizontal: 10, paddingVertical: 6, backgroundColor: 'rgba(255,255,255,.13)' },
  authStepText: { color: '#D8EDDF', fontSize: 10, lineHeight: 14, letterSpacing: 1, fontWeight: '900' },
  authHeroIcon: { width: 43, height: 43, borderRadius: 15, alignItems: 'center', justifyContent: 'center', backgroundColor: 'rgba(255,255,255,.14)', borderWidth: 1, borderColor: 'rgba(255,255,255,.16)' },
  authHeroIconText: { color: authColors.white, fontSize: 20, lineHeight: 23, fontWeight: '900' },
  authHeroTitle: { maxWidth: 310, color: authColors.white, fontSize: 28, lineHeight: 33, fontWeight: '900', letterSpacing: -.8, marginTop: 21 },
  authHeroText: { maxWidth: 310, color: '#C8DED0', fontSize: 13, lineHeight: 20, fontWeight: '600', marginTop: 10 },
  authPanel: { marginTop: 15, padding: 18, borderRadius: 24, borderWidth: 1, borderColor: authColors.line, backgroundColor: authColors.white, shadowColor: '#10261A', shadowOffset: { width: 0, height: 5 }, shadowOpacity: .07, shadowRadius: 12, elevation: 2 },
  panelEyebrow: { color: authColors.green, fontSize: 10, lineHeight: 14, letterSpacing: 1.1, fontWeight: '900' },
  panelTitle: { color: authColors.ink, fontSize: 20, lineHeight: 25, fontWeight: '900', letterSpacing: -.35, marginTop: 4 },
  panelText: { color: authColors.muted, fontSize: 12, lineHeight: 18, fontWeight: '600', marginTop: 5 },
  panelForm: { marginTop: 18, gap: 14 },
  recipientCard: { flexDirection: 'row', alignItems: 'center', padding: 12, borderRadius: 16, backgroundColor: authColors.soft, marginBottom: 17 },
  recipientIcon: { width: 38, height: 38, borderRadius: 13, alignItems: 'center', justifyContent: 'center', backgroundColor: authColors.white },
  recipientIconText: { color: authColors.green, fontSize: 17, fontWeight: '900' },
  recipientCopy: { flex: 1, minWidth: 0, marginLeft: 10 },
  recipientLabel: { color: authColors.green, fontSize: 10, lineHeight: 14, letterSpacing: .7, fontWeight: '900' },
  recipientEmail: { color: authColors.ink, fontSize: 13, lineHeight: 18, fontWeight: '900', marginTop: 2 },
  codeInput: { height: 62, textAlign: 'center', fontSize: 24, lineHeight: 28, letterSpacing: 8, paddingLeft: 23 },
  eyebrow: { color: authColors.green, fontSize: 12, fontWeight: '900', letterSpacing: 1.2 },
  title: { color: authColors.ink, fontSize: 29, lineHeight: 35, fontWeight: '900', letterSpacing: -.8, marginTop: 8 },
  subtitle: { color: authColors.muted, fontSize: 13, lineHeight: 20, fontWeight: '600', marginTop: 9 },
  form: { marginTop: 28, gap: 15 },
  field: { gap: 7 },
  label: { color: authColors.ink, fontSize: 12, fontWeight: '800' },
  input: { height: 54, borderRadius: 16, borderWidth: 1, borderColor: authColors.line, backgroundColor: authColors.white, color: authColors.ink, paddingHorizontal: 16, fontSize: 15, fontWeight: '700' },
  inputError: { borderColor: authColors.danger },
  error: { color: authColors.danger, fontSize: 12, lineHeight: 18, fontWeight: '700' },
  primary: { minHeight: 54, borderRadius: 17, paddingHorizontal: 18, backgroundColor: authColors.green, alignItems: 'center', justifyContent: 'center' },
  primaryPressed: { backgroundColor: authColors.greenDark },
  primaryDisabled: { opacity: .55 },
  primaryText: { color: authColors.white, fontSize: 13, fontWeight: '900' },
  secondary: { minHeight: 54, borderRadius: 17, paddingHorizontal: 18, borderWidth: 1.5, borderColor: authColors.green, alignItems: 'center', justifyContent: 'center', marginTop: 11 },
  secondaryText: { color: authColors.green, fontSize: 13, fontWeight: '900' },
  footerRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', marginTop: 22 },
  footerText: { color: authColors.muted, fontSize: 13, lineHeight: 19, fontWeight: '600' },
  footerLink: { color: authColors.green, fontSize: 13, lineHeight: 19, fontWeight: '900' },
  checkRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10 },
  checkbox: { width: 23, height: 23, borderRadius: 7, borderWidth: 1.5, borderColor: '#AEBBB2', backgroundColor: authColors.white, alignItems: 'center', justifyContent: 'center' },
  checkboxActive: { borderColor: authColors.green, backgroundColor: authColors.green },
  checkmark: { color: authColors.white, fontSize: 13, fontWeight: '900' },
  terms: { flex: 1, color: authColors.muted, fontSize: 12, lineHeight: 18, fontWeight: '600' },
  inlineLink: { color: authColors.green, fontWeight: '900' },
  info: { padding: 14, borderRadius: 15, backgroundColor: authColors.soft, marginTop: 18 },
  infoText: { color: authColors.greenDark, fontSize: 12, lineHeight: 18, fontWeight: '700' },
  setup: { padding: 14, borderRadius: 15, borderWidth: 1, borderColor: '#E9D8A8', backgroundColor: '#FFF9E8', marginTop: 16 },
  setupTitle: { color: '#735A17', fontSize: 12, fontWeight: '900' },
  setupText: { color: '#7D6B38', fontSize: 12, lineHeight: 18, fontWeight: '600', marginTop: 4 },
  successIcon: { width: 68, height: 68, borderRadius: 24, backgroundColor: authColors.soft, alignItems: 'center', justifyContent: 'center', marginTop: 52 },
  successIconText: { color: authColors.green, fontSize: 30, fontWeight: '900' },
});


