[program:dongu-reverb]
command=/usr/bin/php /var/www/dongu/current/artisan reverb:start --host=127.0.0.1 --port=8080
directory=/var/www/dongu/current
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=1
redirect_stderr=true
stdout_logfile=/var/www/dongu/shared/storage/logs/reverb.log
stdout_logfile_maxbytes=20MB
stdout_logfile_backups=5
stopwaitsecs=30
